# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d3af15c84c085cb6c62c7d8840660496ad1fbd45d5498839dd66d5ec053f040f2b7f0904fc73351389ab696bd24a6ddb9ab87ff8886e9eb126bff559502441f

test:
  secret_key_base: aafe7d3dc1f3bea1ea29e24454fa899505bc9d5e127c6450a3502144b39ff7a2c67baec7b50292f7984440a1ec1eb30159fbbde7d9d76da20b3c4295b1b21622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
